# This railway.toml is for the frontend service
# Backend service should use backend/railway.toml with root directory set to backend/

[build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"
buildArgs = ["VITE_SUPABASE_URL=${{VITE_SUPABASE_URL}}", "VITE_SUPABASE_ANON_KEY=${{VITE_SUPABASE_ANON_KEY}}", "VITE_MAPBOX_TOKEN=${{VITE_MAPBOX_TOKEN}}", "VITE_API_URL=${{VITE_API_URL}}"]

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[env]
PORT = "80"