[build]
builder = "dockerfile"
buildArgs = ["VITE_SUPABASE_URL=${{VITE_SUPABASE_URL}}", "VITE_SUPABASE_ANON_KEY=${{VITE_SUPABASE_ANON_KEY}}", "VITE_MAPBOX_TOKEN=${{VITE_MAPBOX_TOKEN}}"]

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[env]
PORT = "80"