[build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"
buildCommand = "cd frontend && docker build -t frontend ."

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[env]
PORT = "80"